### ISSUE TITLE
🎯  VM Conformance - Sprint 3 goals

### ISSUE THREAD

**Issue by raulk** [filecoin-project/oni#224]
This is an umbrella issue capturing the work we have agreed to undertake in Sprint 3.

## Sprint 3 goals

- [ ] Finish 3-way diff: https://github.com/filecoin-project/oni/issues/166 (@willscott)
- [ ] All message-class test cases from chain validation migrated to test vectors.
  - [ ] generate message-class test vectors based on `chain-validation` project: https://github.com/filecoin-project/oni/issues/194 (@nonsense, @alanshaw)
  - [ ] DRY up code through a templating API: https://github.com/filecoin-project/oni/issues/206 (@raulk)
- [ ] We are able to build tipset and chain-class test vectors programmatically.
  - [ ] define schemas (@raulk, others welcome!)
    - [ ] tipset-class: https://github.com/filecoin-project/oni/issues/203
    - [ ] chain-class: https://github.com/filecoin-project/oni/issues/204
    - [ ] figure out preconditions: https://github.com/filecoin-project/oni/issues/174
    - [ ] do we need the block class? https://github.com/filecoin-project/oni/issues/202
  - [ ] chainable dsl: https://github.com/filecoin-project/oni/issues/190
  - [ ] migrate chain validation tipset-class tests: https://github.com/filecoin-project/oni/issues/220
- [ ] Batch runner for generation scripts: https://github.com/filecoin-project/oni/issues/189 (@nonsense)
- [ ] Controlled randomness and verification syscalls, so we can simulate failures. (TBD)
  - controlled randomness: https://github.com/filecoin-project/oni/issues/198
  - controlled verification syscalls: https://github.com/filecoin-project/oni/issues/197
- [ ] We engage ChainSafe and Soramitsu, through a first package to onboard them. (everyone: @alanshaw @nonsense @willscott @raulk)
  - [ ] `filecoin-project/vm-tests` repo created, containing the corpus v0: https://github.com/filecoin-project/oni/issues/221
  - [ ] Test driver has matured and now lives in `filecoin-project/lotus`: https://github.com/filecoin-project/oni/issues/222
  - [ ] CI integration in `filecoin-project/lotus`: https://github.com/filecoin-project/oni/issues/223
- [ ] _Tentative:_ Internal demo on Friday.

## Sprint 3 non-goals

Pushed to later sprints.

- tests targeting the syncer (reorgs, forks, etc.); i.e. blockseq-class test vectors. All tests in scope for Sprint 3 target the VM.
